### PR TITLE
Refactoring #3, #4, and #7.

### LINKED ISSUE #13: Refactoring #3, #4, and #7.
There were some inconsistencies where multiple elements would have the same ID and such. I will switch from styling by ID to styling by class. And adopt suggestions my team members gave.

### PR DESCRIPTION
**Pull request by jiechenmc**
- [x]  refactor html and css

- [x]  use static assets for hobby images

- [x]  change our root path to render "main.jinja"

- [x] change the way that images are loaded

I also made our headings have a rainbow animation, so it won't look too plain for right now.

image

Closes #13.

### CODE REVIEW

**Comment by shawnzhang12** [comment]
Looks great to me! I tried it out and love the rainbow animations. If Lydia is also fine with it, I'm good with merging.

**Comment by jiechenmc** [comment]
I just discovered that the way I was loading my images was not the best practice. I will update it when I get home later today.

**Comment by jiechenmc** [comment]
I think I have gotten everything. I need a final review from @lydiafarag then I think this will be good for merging.

**Comment by lydiafarag** [comment]
Looks Great!

**Pull request merged**
